"""
Trading strategy engine for AegisTrader.
Bi-directional trading logic and signal generation.
"""

import time
import logging
from typing import List, Dict, Optional, Tuple, Any
from dataclasses import dataclass
from enum import Enum
import json
from datetime import datetime, timedelta

from assets import Asset
from scanner.market_scanner import MarketOpportunity, ScanResult
from market_sessions import MarketType

logger = logging.getLogger(__name__)

class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    STRONG_BUY = "strong_buy"
    STRONG_SELL = "strong_sell"
    HOLD = "hold"

class StrategyType(Enum):
    """Types of trading strategies."""
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    PATTERN_RECOGNITION = "pattern_recognition"
    MULTI_TIMEFRAME = "multi_timeframe"

@dataclass
class TradingSignal:
    """Represents a trading signal generated by the strategy engine."""
    asset: Asset
    signal_type: SignalType
    strategy: StrategyType
    confidence: float
    entry_price: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    position_size: float = 0.0
    timeframe: str = "1h"
    reasoning: List[str] = None
    risk_reward_ratio: Optional[float] = None
    timestamp: float = 0.0
    expiry_time: Optional[float] = None

@dataclass
class StrategyConfig:
    """Configuration for trading strategies."""
    enabled_strategies: List[StrategyType]
    risk_per_trade: float = 0.02  # 2% risk per trade
    max_positions: int = 5
    min_confidence: float = 0.7
    min_risk_reward: float = 1.5
    timeframes: List[str] = None
    
    def __post_init__(self):
        if self.timeframes is None:
            self.timeframes = ["1h", "4h", "1D"]

class StrategyEngine:
    """Main strategy engine for generating trading signals."""
    
    def __init__(self, config: Optional[StrategyConfig] = None):
        self.config = config or StrategyConfig(
            enabled_strategies=[StrategyType.MOMENTUM, StrategyType.PATTERN_RECOGNITION]
        )
        
        self.active_signals: List[TradingSignal] = []
        self.signal_history: List[TradingSignal] = []
        
        # Strategy weights for signal combination
        self.strategy_weights = {
            StrategyType.MOMENTUM: 0.3,
            StrategyType.MEAN_REVERSION: 0.2,
            StrategyType.BREAKOUT: 0.25,
            StrategyType.PATTERN_RECOGNITION: 0.4,
            StrategyType.MULTI_TIMEFRAME: 0.35
        }
        
        # Signal strength thresholds
        self.signal_thresholds = {
            SignalType.STRONG_BUY: 0.85,
            SignalType.BUY: 0.7,
            SignalType.HOLD: 0.5,
            SignalType.SELL: 0.7,
            SignalType.STRONG_SELL: 0.85
        }
    
    def analyze_opportunity(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """
        Analyze a market opportunity and generate trading signal.
        
        Args:
            opportunity: Market opportunity from scanner
            scan_result: Detailed scan result for the asset
            
        Returns:
            Trading signal if criteria are met, None otherwise
        """
        signals = []
        
        # Apply enabled strategies
        for strategy_type in self.config.enabled_strategies:
            signal = self._apply_strategy(strategy_type, opportunity, scan_result)
            if signal:
                signals.append(signal)
        
        # Combine signals if multiple strategies agree
        if signals:
            combined_signal = self._combine_signals(signals)
            
            # Validate signal meets minimum criteria
            if self._validate_signal(combined_signal):
                return combined_signal
        
        return None
    
    def _apply_strategy(self, strategy_type: StrategyType, opportunity: MarketOpportunity, 
                       scan_result: ScanResult) -> Optional[TradingSignal]:
        """Apply a specific strategy to generate a signal."""
        
        if strategy_type == StrategyType.MOMENTUM:
            return self._momentum_strategy(opportunity, scan_result)
        elif strategy_type == StrategyType.MEAN_REVERSION:
            return self._mean_reversion_strategy(opportunity, scan_result)
        elif strategy_type == StrategyType.BREAKOUT:
            return self._breakout_strategy(opportunity, scan_result)
        elif strategy_type == StrategyType.PATTERN_RECOGNITION:
            return self._pattern_recognition_strategy(opportunity, scan_result)
        elif strategy_type == StrategyType.MULTI_TIMEFRAME:
            return self._multi_timeframe_strategy(opportunity, scan_result)
        
        return None
    
    def _momentum_strategy(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """Momentum-based trading strategy."""
        if not scan_result.price_data or scan_result.price_data.change_percent is None:
            return None
        
        change_percent = scan_result.price_data.change_percent
        confidence = min(abs(change_percent) / 10.0, 1.0)  # Normalize to 0-1
        
        # Strong momentum signals
        if abs(change_percent) > 5:
            signal_type = SignalType.STRONG_BUY if change_percent > 0 else SignalType.STRONG_SELL
        elif abs(change_percent) > 2:
            signal_type = SignalType.BUY if change_percent > 0 else SignalType.SELL
        else:
            return None
        
        return TradingSignal(
            asset=opportunity.asset,
            signal_type=signal_type,
            strategy=StrategyType.MOMENTUM,
            confidence=confidence,
            entry_price=opportunity.entry_price or 0.0,
            target_price=opportunity.target_price,
            stop_loss=opportunity.stop_loss,
            timeframe=opportunity.timeframe,
            reasoning=[f"Momentum: {change_percent:+.1f}%"],
            timestamp=time.time()
        )
    
    def _mean_reversion_strategy(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """Mean reversion trading strategy."""
        if not scan_result.price_data:
            return None
        
        # Simple mean reversion based on price extremes
        # This would be enhanced with historical price data
        confidence = 0.6  # Base confidence for mean reversion
        
        # Look for oversold/overbought conditions
        if scan_result.price_data.change_percent:
            if scan_result.price_data.change_percent < -8:  # Oversold
                signal_type = SignalType.BUY
                reasoning = ["Mean reversion: Oversold condition"]
            elif scan_result.price_data.change_percent > 8:  # Overbought
                signal_type = SignalType.SELL
                reasoning = ["Mean reversion: Overbought condition"]
            else:
                return None
        else:
            return None
        
        return TradingSignal(
            asset=opportunity.asset,
            signal_type=signal_type,
            strategy=StrategyType.MEAN_REVERSION,
            confidence=confidence,
            entry_price=opportunity.entry_price or 0.0,
            target_price=opportunity.target_price,
            stop_loss=opportunity.stop_loss,
            timeframe=opportunity.timeframe,
            reasoning=reasoning,
            timestamp=time.time()
        )
    
    def _breakout_strategy(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """Breakout trading strategy."""
        # This would analyze support/resistance levels from pattern analysis
        if not scan_result.pattern_analysis:
            return None
        
        patterns = scan_result.pattern_analysis.get('patterns', [])
        breakout_patterns = ['triangle', 'flag', 'pennant', 'channel']
        
        for pattern in patterns:
            if pattern.get('pattern') in breakout_patterns and pattern.get('confidence', 0) > 0.7:
                signal_type = SignalType.BUY if opportunity.signal_type == 'buy' else SignalType.SELL
                
                return TradingSignal(
                    asset=opportunity.asset,
                    signal_type=signal_type,
                    strategy=StrategyType.BREAKOUT,
                    confidence=pattern['confidence'],
                    entry_price=opportunity.entry_price or 0.0,
                    target_price=opportunity.target_price,
                    stop_loss=opportunity.stop_loss,
                    timeframe=opportunity.timeframe,
                    reasoning=[f"Breakout pattern: {pattern['pattern']}"],
                    timestamp=time.time()
                )
        
        return None
    
    def _pattern_recognition_strategy(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """Pattern recognition trading strategy."""
        if not scan_result.pattern_analysis or 'trading_signals' not in scan_result.pattern_analysis:
            return None
        
        pattern_signals = scan_result.pattern_analysis['trading_signals']
        sentiment = pattern_signals.get('overall_sentiment', 'neutral')
        signal_strength = pattern_signals.get('signal_strength', 0.0)
        
        if sentiment == 'bullish' and signal_strength > 0.6:
            signal_type = SignalType.STRONG_BUY if signal_strength > 0.8 else SignalType.BUY
        elif sentiment == 'bearish' and signal_strength > 0.6:
            signal_type = SignalType.STRONG_SELL if signal_strength > 0.8 else SignalType.SELL
        else:
            return None
        
        patterns_detected = [p['pattern'] for p in scan_result.pattern_analysis.get('patterns', [])]
        
        return TradingSignal(
            asset=opportunity.asset,
            signal_type=signal_type,
            strategy=StrategyType.PATTERN_RECOGNITION,
            confidence=signal_strength,
            entry_price=opportunity.entry_price or 0.0,
            target_price=opportunity.target_price,
            stop_loss=opportunity.stop_loss,
            timeframe=opportunity.timeframe,
            reasoning=[f"Patterns: {', '.join(patterns_detected[:3])}"],
            timestamp=time.time()
        )
    
    def _multi_timeframe_strategy(self, opportunity: MarketOpportunity, scan_result: ScanResult) -> Optional[TradingSignal]:
        """Multi-timeframe analysis strategy."""
        # This would analyze multiple timeframes for confluence
        # For now, return a basic signal based on overall score
        
        if scan_result.overall_score > 0.8:
            signal_type = SignalType.STRONG_BUY if opportunity.signal_type == 'buy' else SignalType.STRONG_SELL
        elif scan_result.overall_score > 0.7:
            signal_type = SignalType.BUY if opportunity.signal_type == 'buy' else SignalType.SELL
        else:
            return None
        
        return TradingSignal(
            asset=opportunity.asset,
            signal_type=signal_type,
            strategy=StrategyType.MULTI_TIMEFRAME,
            confidence=scan_result.overall_score,
            entry_price=opportunity.entry_price or 0.0,
            target_price=opportunity.target_price,
            stop_loss=opportunity.stop_loss,
            timeframe=opportunity.timeframe,
            reasoning=["Multi-timeframe confluence"],
            timestamp=time.time()
        )

    def _combine_signals(self, signals: List[TradingSignal]) -> TradingSignal:
        """Combine multiple signals into a single consensus signal."""
        if len(signals) == 1:
            return signals[0]

        # Calculate weighted confidence
        total_weight = 0.0
        weighted_confidence = 0.0

        buy_signals = 0
        sell_signals = 0

        for signal in signals:
            weight = self.strategy_weights.get(signal.strategy, 0.2)
            total_weight += weight
            weighted_confidence += signal.confidence * weight

            if signal.signal_type in [SignalType.BUY, SignalType.STRONG_BUY]:
                buy_signals += 1
            elif signal.signal_type in [SignalType.SELL, SignalType.STRONG_SELL]:
                sell_signals += 1

        # Determine consensus signal type
        if buy_signals > sell_signals:
            consensus_type = SignalType.STRONG_BUY if weighted_confidence > 0.85 else SignalType.BUY
        elif sell_signals > buy_signals:
            consensus_type = SignalType.STRONG_SELL if weighted_confidence > 0.85 else SignalType.SELL
        else:
            consensus_type = SignalType.HOLD

        # Use the first signal as base and update with consensus
        base_signal = signals[0]
        base_signal.signal_type = consensus_type
        base_signal.confidence = weighted_confidence / total_weight if total_weight > 0 else 0.0
        base_signal.strategy = StrategyType.MULTI_TIMEFRAME  # Mark as combined

        # Combine reasoning
        all_reasoning = []
        for signal in signals:
            if signal.reasoning:
                all_reasoning.extend(signal.reasoning)
        base_signal.reasoning = all_reasoning

        return base_signal

    def _validate_signal(self, signal: TradingSignal) -> bool:
        """Validate if a signal meets minimum criteria."""
        # Check minimum confidence
        if signal.confidence < self.config.min_confidence:
            return False

        # Check risk-reward ratio if available
        if signal.risk_reward_ratio and signal.risk_reward_ratio < self.config.min_risk_reward:
            return False

        # Check if signal type meets threshold
        required_confidence = self.signal_thresholds.get(signal.signal_type, 0.5)
        if signal.confidence < required_confidence:
            return False

        return True

    def calculate_position_size(self, signal: TradingSignal, account_balance: float) -> float:
        """
        Calculate position size based on risk management rules.

        Args:
            signal: Trading signal
            account_balance: Current account balance

        Returns:
            Position size in base currency
        """
        if not signal.entry_price or not signal.stop_loss:
            return 0.0

        # Calculate risk per trade
        risk_amount = account_balance * self.config.risk_per_trade

        # Calculate price risk
        if signal.signal_type in [SignalType.BUY, SignalType.STRONG_BUY]:
            price_risk = signal.entry_price - signal.stop_loss
        else:
            price_risk = signal.stop_loss - signal.entry_price

        if price_risk <= 0:
            return 0.0

        # Calculate position size
        position_size = risk_amount / price_risk

        # Apply confidence adjustment
        position_size *= signal.confidence

        return position_size

    def add_signal(self, signal: TradingSignal):
        """Add a new trading signal to active signals."""
        # Set expiry time (default 4 hours)
        if not signal.expiry_time:
            signal.expiry_time = signal.timestamp + (4 * 3600)

        self.active_signals.append(signal)
        self.signal_history.append(signal)

        logger.info(f"Added {signal.signal_type.value} signal for {signal.asset.symbol} "
                   f"(confidence: {signal.confidence:.2f})")

    def remove_expired_signals(self):
        """Remove expired signals from active list."""
        current_time = time.time()
        active_signals = []

        for signal in self.active_signals:
            if signal.expiry_time and current_time < signal.expiry_time:
                active_signals.append(signal)
            else:
                logger.info(f"Expired signal for {signal.asset.symbol}")

        self.active_signals = active_signals

    def get_active_signals(self, asset: Optional[Asset] = None) -> List[TradingSignal]:
        """Get active trading signals, optionally filtered by asset."""
        self.remove_expired_signals()

        if asset:
            return [s for s in self.active_signals if s.asset.symbol == asset.symbol]

        return self.active_signals.copy()

    def get_signal_summary(self) -> Dict[str, Any]:
        """Get summary of current signals and strategy performance."""
        self.remove_expired_signals()

        signal_counts = {}
        for signal_type in SignalType:
            signal_counts[signal_type.value] = len([
                s for s in self.active_signals if s.signal_type == signal_type
            ])

        strategy_counts = {}
        for strategy_type in StrategyType:
            strategy_counts[strategy_type.value] = len([
                s for s in self.active_signals if s.strategy == strategy_type
            ])

        avg_confidence = 0.0
        if self.active_signals:
            avg_confidence = sum(s.confidence for s in self.active_signals) / len(self.active_signals)

        return {
            'active_signals': len(self.active_signals),
            'signal_breakdown': signal_counts,
            'strategy_breakdown': strategy_counts,
            'average_confidence': avg_confidence,
            'total_signals_generated': len(self.signal_history),
            'top_signals': [
                {
                    'symbol': s.asset.symbol,
                    'signal': s.signal_type.value,
                    'confidence': s.confidence,
                    'strategy': s.strategy.value
                }
                for s in sorted(self.active_signals, key=lambda x: x.confidence, reverse=True)[:5]
            ]
        }

# Global strategy engine instance
strategy_engine = None

def get_strategy_engine() -> StrategyEngine:
    """Get the global strategy engine instance."""
    global strategy_engine
    if strategy_engine is None:
        strategy_engine = StrategyEngine()
    return strategy_engine

if __name__ == "__main__":
    # Test the strategy engine
    engine = StrategyEngine()

    print("Strategy Engine Test")
    print("=" * 30)
    print(f"Enabled strategies: {[s.value for s in engine.config.enabled_strategies]}")
    print(f"Min confidence: {engine.config.min_confidence}")
    print(f"Risk per trade: {engine.config.risk_per_trade * 100}%")

    summary = engine.get_signal_summary()
    print(f"\nCurrent signals: {summary['active_signals']}")
    print(f"Total generated: {summary['total_signals_generated']}")
